/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OperatorRouteImport } from './routes/operator'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OperatorIndexRouteImport } from './routes/operator.index'
import { Route as AdminRecipesRouteImport } from './routes/admin.recipes'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminCollaboratorsRouteImport } from './routes/admin.collaborators'
import { Route as AdminCalculatorRouteImport } from './routes/admin.calculator'
import { Route as OperatorRecipeIdRouteImport } from './routes/operator.recipe.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRoute = OperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorIndexRoute = OperatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OperatorRoute,
} as any)
const AdminRecipesRoute = AdminRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollaboratorsRoute = AdminCollaboratorsRouteImport.update({
  id: '/collaborators',
  path: '/collaborators',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalculatorRoute = AdminCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => AdminRoute,
} as any)
const OperatorRecipeIdRoute = OperatorRecipeIdRouteImport.update({
  id: '/recipe/$id',
  path: '/recipe/$id',
  getParentRoute: () => OperatorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/operator': typeof OperatorRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin/calculator': typeof AdminCalculatorRoute
  '/admin/collaborators': typeof AdminCollaboratorsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/recipes': typeof AdminRecipesRoute
  '/operator/': typeof OperatorIndexRoute
  '/operator/recipe/$id': typeof OperatorRecipeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/calculator': typeof AdminCalculatorRoute
  '/admin/collaborators': typeof AdminCollaboratorsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/recipes': typeof AdminRecipesRoute
  '/operator': typeof OperatorIndexRoute
  '/operator/recipe/$id': typeof OperatorRecipeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/operator': typeof OperatorRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin/calculator': typeof AdminCalculatorRoute
  '/admin/collaborators': typeof AdminCollaboratorsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/recipes': typeof AdminRecipesRoute
  '/operator/': typeof OperatorIndexRoute
  '/operator/recipe/$id': typeof OperatorRecipeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/operator'
    | '/reset-password'
    | '/admin/calculator'
    | '/admin/collaborators'
    | '/admin/logs'
    | '/admin/recipes'
    | '/operator/'
    | '/operator/recipe/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/reset-password'
    | '/admin/calculator'
    | '/admin/collaborators'
    | '/admin/logs'
    | '/admin/recipes'
    | '/operator'
    | '/operator/recipe/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/operator'
    | '/reset-password'
    | '/admin/calculator'
    | '/admin/collaborators'
    | '/admin/logs'
    | '/admin/recipes'
    | '/operator/'
    | '/operator/recipe/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  OperatorRoute: typeof OperatorRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/': {
      id: '/operator/'
      path: '/'
      fullPath: '/operator/'
      preLoaderRoute: typeof OperatorIndexRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/admin/recipes': {
      id: '/admin/recipes'
      path: '/recipes'
      fullPath: '/admin/recipes'
      preLoaderRoute: typeof AdminRecipesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collaborators': {
      id: '/admin/collaborators'
      path: '/collaborators'
      fullPath: '/admin/collaborators'
      preLoaderRoute: typeof AdminCollaboratorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calculator': {
      id: '/admin/calculator'
      path: '/calculator'
      fullPath: '/admin/calculator'
      preLoaderRoute: typeof AdminCalculatorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/operator/recipe/$id': {
      id: '/operator/recipe/$id'
      path: '/recipe/$id'
      fullPath: '/operator/recipe/$id'
      preLoaderRoute: typeof OperatorRecipeIdRouteImport
      parentRoute: typeof OperatorRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCalculatorRoute: typeof AdminCalculatorRoute
  AdminCollaboratorsRoute: typeof AdminCollaboratorsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminRecipesRoute: typeof AdminRecipesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCalculatorRoute: AdminCalculatorRoute,
  AdminCollaboratorsRoute: AdminCollaboratorsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminRecipesRoute: AdminRecipesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OperatorRouteChildren {
  OperatorIndexRoute: typeof OperatorIndexRoute
  OperatorRecipeIdRoute: typeof OperatorRecipeIdRoute
}

const OperatorRouteChildren: OperatorRouteChildren = {
  OperatorIndexRoute: OperatorIndexRoute,
  OperatorRecipeIdRoute: OperatorRecipeIdRoute,
}

const OperatorRouteWithChildren = OperatorRoute._addFileChildren(
  OperatorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  OperatorRoute: OperatorRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
